modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"

[[mods]] #mandatory
    modId="inconvein" #mandatory
    version="0.0.2-1.18.2" #mandatory
    displayName="Inconvein" #mandatory
    logoFile="examplemod.png" #optional
    credits="Nokunami" #optional
    authors="Nokunami" #optional
    description='''
    Adds materials to the inconvein modpack.
    '''


[[dependencies.inconvein]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.inconvein]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"

[[dependencies.inconvein]]
    modId="catalogue"
    mandatory=false
    versionRange="[1.6.2,)"
    ordering="NONE"
    side="CLIENT"

[[dependencies.inconvein]]
    modId="jei"
    mandatory=false
    versionRange="[9.7.2,)"
    ordering="NONE"
    side="CLIENT"

[modproperties.inconvein]
#Catalogue also supports items. Use "catalogueItemIcon" instead.
catalogueItemIcon="inconvein:ancient_metal_scrap" #Optional support for Cataloque mod.
configuredBackground="inconvein:textures/block/diarkrite_block.png" #Optional support for Configured mod.